# Generated by Django 2.2.3 on 2019-07-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=50)),
                ('camapaign', models.CharField(max_length=50)),
                ('campaign_id', models.CharField(max_length=6000)),
            ],
        ),
    ]
